#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
使用AI自动生成模板样例内容
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# 设置API密钥
os.environ['ZHIPU_API_KEY'] = 'd6ac02f8c1f6f443cf81f3dae86fb095.7Qe6KOWcVDlDlqDJ'
os.environ['AI_PROVIDER'] = 'zhipu'

from config import Config
from services.ai_service import AIService
from services.prompt_template_service import PromptTemplateService
import logging
import json

logging.basicConfig(level=logging.INFO, format='%(message)s')
logger = logging.getLogger(__name__)


def generate_tech_zhihu_template():
    """生成科技公司-知乎模板"""
    logger.info("\n=== Generating Tech Company + Zhihu Template ===\n")

    config = Config()
    ai_service = AIService(config)

    # 使用AI生成system prompt
    prompt = """
请为"科技公司在知乎平台推广"场景设计一个完整的AI提示词模板。

要求：
1. 包含两个阶段：分析阶段(analysis)和文章生成阶段(article_generation)
2. 每个阶段都要有system prompt和user template
3. system prompt要定义AI的角色和专业背景
4. user template要包含变量（用{{variable}}格式），如{{company_name}}, {{company_desc}}, {{analysis}}, {{angle}}等
5. 符合知乎平台的专业、深度、客观的风格
6. 适合科技行业的技术分析视角

请直接返回JSON格式，结构如下：
{
  "analysis": {
    "system": "系统提示词...",
    "user_template": "用户提示词模板，包含{{company_name}}等变量..."
  },
  "article_generation": {
    "system": "系统提示词...",
    "user_template": "用户提示词模板..."
  }
}
"""

    messages = [
        {'role': 'user', 'content': prompt}
    ]

    try:
        result = ai_service._call_api(messages, temperature=0.7, max_tokens=2000)
        logger.info("AI Generated Prompts:")
        logger.info(result)

        # 尝试解析JSON
        try:
            # 提取JSON部分
            import re
            json_match = re.search(r'\{.*\}', result, re.DOTALL)
            if json_match:
                prompts = json.loads(json_match.group())
            else:
                logger.warning("Cannot extract JSON, using raw result")
                prompts = None
        except:
            logger.warning("Failed to parse JSON from AI response")
            prompts = None

        # 创建模板数据
        template_data = {
            'name': 'Tech Company - Zhihu Analysis Template',
            'code': 'tech_zhihu_v1',
            'category_id': None,
            'prompts': prompts or {
                'analysis': {
                    'system': '你是一个资深的科技行业分析师，有10年的科技公司研究经验。',
                    'user_template': '请深入分析以下科技公司：\\n\\n公司名称：{{company_name}}\\n公司描述：{{company_desc}}'
                },
                'article_generation': {
                    'system': '你是知乎科技领域的优秀回答者。',
                    'user_template': '基于以下分析，撰写知乎文章：\\n{{analysis}}'
                }
            },
            'industry_tags': ['tech', 'ai', 'cloud'],
            'platform_tags': ['zhihu'],
            'keywords': ['AI', 'Cloud Computing', 'Innovation', 'Technology'],
            'ai_config': {
                'temperature': 0.8,
                'max_tokens': 3000,
                'model': 'glm-4-flash'
            },
            'version': '1.0',
            'status': 'active',
            'description': 'Template for analyzing tech companies and generating Zhihu articles',
            'example_company': 'Huawei Cloud',
            'notes': 'Auto-generated by AI'
        }

        # 保存模板
        template = PromptTemplateService.create_template(template_data, user_id=1)
        logger.info(f"\n✓ Template created successfully: ID={template['id']}")

        return template

    except Exception as e:
        logger.error(f"Failed to generate template: {e}")
        import traceback
        traceback.print_exc()
        return None


def generate_finance_template():
    """生成金融公司模板"""
    logger.info("\n=== Generating Finance Company Template ===\n")

    template_data = {
        'name': 'Finance Company - General Template',
        'code': 'finance_general_v1',
        'prompts': {
            'analysis': {
                'system': '你是一个金融行业专家，熟悉金融科技、合规、风控等领域。',
                'user_template': '请分析以下金融公司：\\n\\n公司：{{company_name}}\\n描述：{{company_desc}}\\n\\n重点关注：合规性、风控能力、安全性'
            },
            'article_generation': {
                'system': '你是一个专业的金融内容创作者。',
                'user_template': '基于分析{{analysis}}，为{{company_name}}撰写专业文章，角度：{{angle}}'
            }
        },
        'industry_tags': ['finance', 'fintech'],
        'platform_tags': ['zhihu', 'wechat'],
        'keywords': ['Finance', 'Compliance', 'Risk Control', 'Security'],
        'ai_config': {'temperature': 0.7, 'max_tokens': 2500},
        'status': 'active',
        'description': 'Template for finance companies'
    }

    try:
        template = PromptTemplateService.create_template(template_data, user_id=1)
        logger.info(f"✓ Finance template created: ID={template['id']}")
        return template
    except Exception as e:
        logger.error(f"Failed: {e}")
        return None


def generate_education_template():
    """生成教育行业模板"""
    logger.info("\n=== Generating Education Template ===\n")

    template_data = {
        'name': 'Education - Online Learning Template',
        'code': 'education_online_v1',
        'prompts': {
            'analysis': {
                'system': '你是教育行业专家，了解在线教育、K12、职业培训等领域。',
                'user_template': '分析教育机构：{{company_name}}\\n{{company_desc}}\\n\\n关注：教学质量、师资、学习效果'
            },
            'article_generation': {
                'system': '你是教育领域的内容创作者。',
                'user_template': '为{{company_name}}撰写文章\\n分析：{{analysis}}\\n角度：{{angle}}'
            }
        },
        'industry_tags': ['education', 'online-learning'],
        'platform_tags': ['zhihu', 'wechat', 'xiaohongshu'],
        'keywords': ['Education', 'Online Learning', 'Quality'],
        'ai_config': {'temperature': 0.75, 'max_tokens': 2500},
        'status': 'active',
        'description': 'Template for education companies'
    }

    try:
        template = PromptTemplateService.create_template(template_data, user_id=1)
        logger.info(f"✓ Education template created: ID={template['id']}")
        return template
    except Exception as e:
        logger.error(f"Failed: {e}")
        return None


def main():
    """主函数"""
    logger.info("="*60)
    logger.info("Template Sample Generator - Using AI")
    logger.info("="*60)

    templates_created = []

    # 生成3个模板
    t1 = generate_tech_zhihu_template()
    if t1:
        templates_created.append(t1)

    t2 = generate_finance_template()
    if t2:
        templates_created.append(t2)

    t3 = generate_education_template()
    if t3:
        templates_created.append(t3)

    logger.info("\n" + "="*60)
    logger.info(f"Summary: {len(templates_created)} templates created")
    logger.info("="*60)

    for t in templates_created:
        logger.info(f"  - {t['name']} (ID: {t['id']}, Code: {t['code']})")

    logger.info("\nTemplates are now available in the system!")
    logger.info("You can use them via API or integrate into the UI.")


if __name__ == '__main__':
    main()
