#!/bin/bash
# 升级服务器Python到最新版本的命令

# 服务器信息
SERVER="39.105.12.124"
USER="u_topn"
PASSWORD="TopN@2024"

echo "=== 准备连接到服务器 $SERVER ==="
echo "用户名: $USER"
echo ""
echo "请执行以下命令连接到服务器并升级Python："
echo ""
echo "ssh $USER@$SERVER"
echo "密码: $PASSWORD"
echo ""
echo "连接成功后，执行以下命令："
echo ""
echo "# 1. 检查当前Python版本"
echo "python3 --version"
echo ""
echo "# 2. 更新系统包列表"
echo "sudo yum update -y  # CentOS/RHEL"
echo "# 或"
echo "sudo apt update -y  # Ubuntu/Debian"
echo ""
echo "# 3. 安装最新Python 3.13（从源码编译）"
echo "sudo yum install -y gcc openssl-devel bzip2-devel libffi-devel zlib-devel  # CentOS/RHEL"
echo "# 或"
echo "sudo apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget  # Ubuntu/Debian"
echo ""
echo "cd /tmp"
echo "wget https://www.python.org/ftp/python/3.13.1/Python-3.13.1.tgz"
echo "tar -xzf Python-3.13.1.tgz"
echo "cd Python-3.13.1"
echo "./configure --enable-optimizations"
echo "sudo make altinstall"
echo ""
echo "# 4. 验证安装"
echo "python3.13 --version"
echo "sudo ln -sf /usr/local/bin/python3.13 /usr/bin/python3"
echo "python3 --version"
